name: A workflow for my Hello Alex file
on: push
jobs:
  build:
    name: Hello Alex action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Alex"
